-- MySQL Script generated by MySQL Workbench
-- 04/19/16 19:04:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema JoinSchema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `JoinSchema` ;

-- -----------------------------------------------------
-- Schema JoinSchema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JoinSchema` DEFAULT CHARACTER SET latin1 ;
USE `JoinSchema` ;

-- -----------------------------------------------------
-- Table `JoinSchema`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`User` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`User` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `TimeZone` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `UserID_UNIQUE` ON `JoinSchema`.`User` (`UserID` ASC);

CREATE UNIQUE INDEX `Email_UNIQUE` ON `JoinSchema`.`User` (`Email` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Available Hour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Available Hour` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Available Hour` (
  `HourID` INT(11) NOT NULL,
  `Day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HourID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `JoinSchema`.`Available`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Available` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Available` (
  `UserID` INT(11) NULL DEFAULT NULL,
  `HourID` INT(11) NULL DEFAULT NULL,
  CONSTRAINT `Available_User`
    FOREIGN KEY (`UserID`)
    REFERENCES `JoinSchema`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Available_Hour`
    FOREIGN KEY (`HourID`)
    REFERENCES `JoinSchema`.`Available Hour` (`HourID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `Available_User_idx` ON `JoinSchema`.`Available` (`UserID` ASC);

CREATE INDEX `Available_Hour_idx` ON `JoinSchema`.`Available` (`HourID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Message` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Message` (
  `MessageID` INT(10) NOT NULL AUTO_INCREMENT,
  `TimeStamp` VARCHAR(45) NULL DEFAULT NULL,
  `Contents` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MessageID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `MessageID_UNIQUE` ON `JoinSchema`.`Message` (`MessageID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Comes From`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Comes From` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Comes From` (
  `UserID` INT(11) NULL DEFAULT NULL,
  `MessageID` INT(11) NULL DEFAULT NULL,
  CONSTRAINT `Comes_From_User_FK`
    FOREIGN KEY (`UserID`)
    REFERENCES `JoinSchema`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Comes_From_Message_FK`
    FOREIGN KEY (`MessageID`)
    REFERENCES `JoinSchema`.`Message` (`MessageID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `Comes_From_User_idx` ON `JoinSchema`.`Comes From` (`UserID` ASC);

CREATE INDEX `Comes_From_Message_FK_idx` ON `JoinSchema`.`Comes From` (`MessageID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Game` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Game` (
  `GameID` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL DEFAULT NULL,
  `Price` VARCHAR(45) NULL DEFAULT NULL,
  `Rating` VARCHAR(45) NULL DEFAULT NULL,
  `Platform` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`GameID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `GameID_UNIQUE` ON `JoinSchema`.`Game` (`GameID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Gaming Accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Gaming Accounts` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Gaming Accounts` (
  `GameAccountID` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`GameAccountID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `GameAccountID_UNIQUE` ON `JoinSchema`.`Gaming Accounts` (`GameAccountID` ASC);

CREATE UNIQUE INDEX `UserName_UNIQUE` ON `JoinSchema`.`Gaming Accounts` (`UserName` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Goes_To`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Goes_To` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Goes_To` (
  `UserID` INT(11) NULL DEFAULT NULL,
  `MessageID` INT(11) NULL DEFAULT NULL,
  CONSTRAINT `Goes_To_Message`
    FOREIGN KEY (`MessageID`)
    REFERENCES `JoinSchema`.`Message` (`MessageID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Goes_To_User`
    FOREIGN KEY (`UserID`)
    REFERENCES `JoinSchema`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `Goes_To_User_idx` ON `JoinSchema`.`Goes_To` (`UserID` ASC);

CREATE INDEX `Goes_To_Message_idx` ON `JoinSchema`.`Goes_To` (`MessageID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Preference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Preference` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Preference` (
  `PreferenceID` INT(10) NOT NULL AUTO_INCREMENT,
  `FavoriteGenre` VARCHAR(45) NULL DEFAULT NULL,
  `FavoritePlatform` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PreferenceID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `PreferenceID_UNIQUE` ON `JoinSchema`.`Preference` (`PreferenceID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Has`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Has` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Has` (
  `PreferenceID` INT(11) NULL DEFAULT NULL,
  `UserID` INT(11) NULL DEFAULT NULL,
  CONSTRAINT `Has_Preference_FK`
    FOREIGN KEY (`PreferenceID`)
    REFERENCES `JoinSchema`.`Preference` (`PreferenceID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Has_UserID_FK`
    FOREIGN KEY (`UserID`)
    REFERENCES `JoinSchema`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `Has_Preference_FK_idx` ON `JoinSchema`.`Has` (`PreferenceID` ASC);

CREATE INDEX `Has_UserID_FK_idx` ON `JoinSchema`.`Has` (`UserID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Tag` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Tag` (
  `TagID` INT(11) NOT NULL AUTO_INCREMENT,
  `TagName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TagID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `TagID_UNIQUE` ON `JoinSchema`.`Tag` (`TagID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Have`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Have` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Have` (
  `GameID` INT(11) NULL DEFAULT NULL,
  `TagID` INT(11) NULL DEFAULT NULL,
  CONSTRAINT `Have_Game_FK`
    FOREIGN KEY (`GameID`)
    REFERENCES `JoinSchema`.`Game` (`GameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Have_Tag_FK`
    FOREIGN KEY (`TagID`)
    REFERENCES `JoinSchema`.`Tag` (`TagID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `GameID_idx` ON `JoinSchema`.`Have` (`GameID` ASC);

CREATE INDEX `Have_Tag_FK_idx` ON `JoinSchema`.`Have` (`TagID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Owns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Owns` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Owns` (
  `GameID` INT(11) NULL DEFAULT NULL,
  `UserID` INT(11) NULL DEFAULT NULL,
  CONSTRAINT `Owns_Game_FK`
    FOREIGN KEY (`GameID`)
    REFERENCES `JoinSchema`.`Game` (`GameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Owns_User_FK`
    FOREIGN KEY (`UserID`)
    REFERENCES `JoinSchema`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `Owns_Game_FK_idx` ON `JoinSchema`.`Owns` (`GameID` ASC);

CREATE INDEX `Owns_User_FK_idx` ON `JoinSchema`.`Owns` (`UserID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Play As`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Play As` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Play As` (
  `UserID` INT(11) NULL DEFAULT NULL,
  `GameAccountID` INT(11) NULL DEFAULT NULL,
  CONSTRAINT `Play_As_GA_FK`
    FOREIGN KEY (`GameAccountID`)
    REFERENCES `JoinSchema`.`Game` (`GameID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Play_As_User_FK`
    FOREIGN KEY (`UserID`)
    REFERENCES `JoinSchema`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `Play_As_User_FK_idx` ON `JoinSchema`.`Play As` (`UserID` ASC);

CREATE INDEX `Play_As_GA_FK_idx` ON `JoinSchema`.`Play As` (`GameAccountID` ASC);


-- -----------------------------------------------------
-- Table `JoinSchema`.`Rates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JoinSchema`.`Rates` ;

CREATE TABLE IF NOT EXISTS `JoinSchema`.`Rates` (
  `UserRateID` INT(11) NULL DEFAULT NULL,
  `UserRatedID` INT(11) NULL DEFAULT NULL,
  `SCORE` INT(11) NULL DEFAULT NULL,
  CONSTRAINT `Rates_User_FK2`
    FOREIGN KEY (`UserRatedID`)
    REFERENCES `JoinSchema`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Rates_User_FK1`
    FOREIGN KEY (`UserRateID`)
    REFERENCES `JoinSchema`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `Rates_User_FK_idx` ON `JoinSchema`.`Rates` (`UserRateID` ASC);

CREATE INDEX `Rates_User_FK2_idx` ON `JoinSchema`.`Rates` (`UserRatedID` ASC);

USE `JoinSchema`;

DELIMITER $$

USE `JoinSchema`$$
DROP TRIGGER IF EXISTS `JoinSchema`.`password_check` $$
USE `JoinSchema`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `JoinSchema`.`password_check`
BEFORE INSERT ON `JoinSchema`.`User`
FOR EACH ROW
BEGIN
	IF CHAR_LENGTH(New.Password) < 8 THEN 
    SIGNAL SQLSTATE '12345'
		SET MESSAGE_TEXT = 'A password must be at least 8 characters long';
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
